### ISSUE TITLE
Unable to use with Typescript

### ISSUE THREAD

**Issue by mdougherty3** [jairoblatt/vue3-radial-progress#4]
I receive an error 'Cannot find module 'vue3-radial-progress' or its corresponding type declarations.ts(2307)' when trying to use this library with typescript.

![Screenshot-20211119150340-820x100](https://user-images.githubusercontent.com/48739541/142684796-e827cf8d-cd60-4d95-86b4-90cf43285b8f.png)

**Comment by jairoblatt** [comment]
Thanks for the report, please update to `vue3-radial-progress@1.0.6` and let me know if it worked for you

**Comment by mdougherty3** [comment]
Works great now, thanks!
