### ISSUE TITLE
startColor, stopColor gradient not working correctly when the component is used multiple times in same page.

### ISSUE THREAD

**Issue by AntGK** [jairoblatt/vue3-radial-progress#7]
Looks like the gradient definition id in svg defs is not unique.  Browser picking up first id, when used multiple times.

**Comment by jairoblatt** [comment]
Hi thanks for report, can you send me an example? I couldn't find this bug.

**Comment by jairoblatt** [comment]
Fixed! Update your package to [1.1.1](https://www.npmjs.com/package/vue3-radial-progress/v/1.1.1)

**Comment by AntGK** [comment]
Cool, thanks
